version: 2.1

orbs:
  codacy: codacy/base@10.2.2
  codacy_plugins_test: codacy/plugins-test@1.1.1

jobs:
  unit_test:
    docker: # run the steps with Docker
      - image: crystallang/crystal:1.8.2
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/workdir
      - run:
          name: Install dependencies
          command: shards install
      - run:
          name: Run test
          command: crystal spec

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - codacy/checkout_and_version
      - unit_test:
          requires:
            - codacy/checkout_and_version
      - codacy/shell:
          name: publish_local
          cmd: |
            docker build -t $CIRCLE_PROJECT_REPONAME:latest .
            docker save --output docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
          persist_to_workspace: true
          requires:
            - codacy/checkout_and_version
      - codacy_plugins_test/run:
          name: plugins_test
          run_multiple_tests: true
          requires:
            - publish_local
      - codacy/publish_docker:
          filters:
            branches:
              only: master
          requires:
            - unit_test
            - publish_local
            - plugins_test
      - codacy/tag_version:
          context: CodacyAWS
          requires:
            - codacy/publish_docker
